- name: generate SSH key
  hosts: 127.0.0.1
  connection: local

  vars:
    default_account_ssh_key_filename: orangepi
    vnc_account_ssh_key_filename: rmdt
    service_account_ssh_key_filename: ansible

  tasks:

    - name: install the python and pip packages (Debian)
      apt:
        name:
          - python3
          - python3-pip
        state: latest
      when: ansible_distribution == "Debian"

    - name: Install the crypto python package
      ansible.builtin.pip:
        name: cryptography[ssh]
        state: latest
      when: ansible_distribution == "Debian"


    - name: generate SSH key "{{default_account_ssh_key_filename}}"
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{default_account_ssh_key_filename}}"
        passphrase: super_secret_password
        type: ed25519
        state: present
        force: no

    - name: generate SSH key "{{vnc_account_ssh_key_filename}}"
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{vnc_account_ssh_key_filename}}"
        passphrase: super_secret_password
        type: ed25519
        state: present
        force: no

    - name: generate SSH key "{{service_account_ssh_key_filename}}"
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{service_account_ssh_key_filename}}"
        type: ed25519
        state: present
        force: no
