- name: generate SSH key
  hosts: 127.0.0.1
  connection: local

  vars:
    users_to_create:
      - user_name: orangepi
        passphrase: super_secret_password
        has_sudo: yes
      - user_name: rmdt
        passphrase: super_secret_password
        has_sudo: no
      - user_name: ansible
        passphrase:
        has_sudo: yes

  tasks:

    - name: Userlist filtered to those whith sudo
      debug:
        var: item.user_name
      loop: "{{ users_to_create|json_query('[?\"has_sudo\"]') }}"

#    - meta: end_play

    - name: install the python and pip packages (Debian)
      apt:
        name:
          - python3
          - python3-pip
        state: latest
      when: ansible_distribution == "Debian"

    - name: Install the crypto python package
      ansible.builtin.pip:
        name: cryptography[ssh]
        state: latest
      when: ansible_distribution == "Debian"

    - name: Generate SSH keys for use with Ansible
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{ item.user_name }}"
        passphrase: "{{ item.passphrase }}"
        type: ed25519
        state: present
        force: no
      loop: "{{ users_to_create }}"
