 - hosts: VM_homebridgeservers
   remote_user: root
   become: true
   pre_tasks:

   - name: upgrade distro and apt cache
     tags: always
     apt:
       upgrade: dist
       update_cache: yes

   - name: Ensure 'ntp' package is removed
     ansible.builtin.apt:
       name: ntp
       state: absent

   - name: Ensure systemd-timesyncd is installed
     ansible.builtin.apt:
       name: systemd-timesyncd
       cache_valid_time: 3600
       state: present

   - name: Make sure "systemd-timesyncd" is enabled
     ansible.builtin.systemd:
       name: systemd-timesyncd
       state: started
       enabled: true

   - name: Turning "set-ntp" on
     ansible.builtin.command: /usr/bin/timedatectl set-ntp on

   - name: Set timezone to Europe/Prague
     community.general.timezone:
       name: Europe/Prague

   - name: install the acl package (enables users to become unprivileged users)
     tags: always
     ansible.builtin.apt:
       name:
         - "acl"
       state: latest
       cache_valid_time: 3600

   - name: sync time on the target machine
     ansible.builtin.command: 'date -s "{{ ansible_date_time.iso8601 }}"'
#     register: datesetto

#   - debug:
#       var: datesetto.stdout_lines

   - name: install the uncomplicated firewall ufw package
     tags: always
     ansible.builtin.apt:
       name:
         - "ufw"
       state: latest
       cache_valid_time: 3600

   - name: Set ufw to deny everything but keep it disabled
     community.general.ufw:
       state: disabled
       policy: deny

   - name: Allow SSH access
     community.general.ufw:
       rule: allow
       name: OpenSSH

   - name: Deny in access to tcp port 80
     community.general.ufw:
       rule: deny
       direction: in
       port: '80'

   - name: Allow in access to tcp port 8581
     community.general.ufw:
       rule: allow
       direction: in
       port: '8581'
       proto: tcp

   - name: Allow in access to port 1880
     community.general.ufw:
       rule: allow
       direction: in
       port: '1880'

   - name: Enable UFW
     community.general.ufw:
       state: enabled

#The above UFW settings will result in the following 'ufw status' response: 

#To				Action		From
#--				------		----
#[ 1] OpenSSH			ALLOW IN	Anywhere
#[ 2] 8581/tcp			ALLOW IN	Anywhere
#[ 3] 1880			ALLOW IN	Anywhere
#[ 4] 80			DENY IN		Anywhere
#[ 5] OpenSSH (v6)		ALLOW IN	Anywhere (v6)
#[ 6] 8581/tcp (v6)		ALLOW IN	Anywhere (v6)
#[ 7] 1880 (v6)			ALLOW IN	Anywhere (v6)
#[ 8] 80 (v6)			DENY IN		Anywhere (v6)

