---

- hosts: VM_homebridge_devices
  become: true
  tasks:

  - name: update repository cache, then remove apache
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
    when: ansible_distribution == "Debian"
