---

- hosts: homebridge_devices
  become: true
  tasks:

  - name: update repository cache, then install apache along with php support
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
    when: ansible_distribution == "Debian"
