 - hosts: all
   become: true
   pre_tasks:

   - name: update repository index (Debian)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Debian"

 - hosts: all
   become: true
   tasks:

   - name: Remove the user 'simone'
     ansible.builtin.user:
       name: simone
       state: absent
       remove: yes
